spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://aa1m3mdjaffkm9p.cseptnqmesu2.us-west-2.rds.amazonaws.com:3306/ebdb?useUnicode=true&characterEncoding=utf-8
    username: root
#    password: 123456
    password: 1234566qqq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.zhengda.blog: debug
  file: log/blog-dev.log








